version: '3.8'
services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: mael
      MYSQL_PASSWORD: password_mael
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql://mael:password_mael@db/portfolio_db
